name: Incorrect information
description: Report incorrect information in the Wiki
labels:
  - "incorrect"
body:
  - type: input
    id: url
    attributes:
      label: "URL to the Wiki page"
      placeholder: "https://github.com/qdm12/gluetun-wiki/blob/main/README.md"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What's incorrect?"
    validations:
      required: true
