name: Misleading information
description: Misleading information in the Wiki
labels:
  - "misleading"
body:
  - type: input
    id: url
    attributes:
      label: "URL to the Wiki page"
      placeholder: "https://github.com/qdm12/gluetun-wiki/blob/main/README.md"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: "What's misleading?"
    validations:
      required: true
